# Generated by Django 4.2.5 on 2023-09-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0002_alter_form_mail_alter_form_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='mail',
            new_name='email',
        ),
    ]
