# Ausführen einer Go-Datei auf einem Webserver mit einem Multistage-Dockerfile
# Gesamtgröße des Image: ~ 14MB (!)

FROM golang:1.17-alpine AS stage
WORKDIR /app
COPY src ./
RUN go build -o main

FROM alpine
WORKDIR /app
# hier wird die Binärdatei von dem golang-Container in einen alpine-Container kopiert
COPY --from=stage /app/main ./
EXPOSE 8080
CMD [ "./main" ]
